#pragma once
#define Name_IDLE				L"IDLE"
#define Name_Run				L"Run"
#define Name_DashBack			L"DashBack"
#define Name_Arsenal_Charge		L"Arsenal_Charge"
#define Name_Arsenal_Loop		L"Arsenal_Loop"
#define Name_Arsenal_End		L"Arsenal_End"
#define Name_Escape_Out			L"Escape_Out"
#define Name_Escape_In			L"Escape_In"
#define Name_Evade_Left			L"Evade_Left"
#define Name_Evade_Right		L"Evade_Right"
#define Name_Attack_1			L"Attack_1"
#define Name_Shoot_1			L"Shoot_1"
#define Name_Shoot_2			L"Shoot_2"
#define Name_Shoot_3			L"Shoot_3"
#define Name_Shock_1			L"Shock_1"
#define Name_Shock_2			L"Shock_2"
#define Name_Shock_2_Boom		L"Shock_2_Boom"
#define Name_Shock_2_Miss		L"Shock_2_Miss"
#define Name_Stealth_Back		L"Stealth_Back"
#define Name_Snealth			L"Snealth"
#define Name_Summon				L"Summon"
#define Name_Throw_1			L"Throw_1"
#define Name_Throw_2			L"Throw_2"
#define Name_Throw_3			L"Throw_3"
#define Name_Skill_Ultra		L"Skill_Ultra"
#define Name_Weak				L"Weak"
#define Name_Weak_Hit_L			L"Weak_Hit_L"
#define Name_Weak_Hit_H			L"Weak_Hit_H"
#define Name_Weak_Start_L		L"Weak_Start_L"
#define Name_Weak_Start_H		L"Weak_Start_H"
#define Name_Hit_H				L"Hit_H"
#define Name_Die				L"Die"

#define Index_IDLE				0
#define Index_Run				1
#define Index_DashBack			2
#define Index_Arsenal_Charge	3
#define Index_Arsenal_Loop		4
#define Index_Arsenal_End		5
#define Index_Escape_Out		6
#define Index_Escape_In			7
#define Index_Evade_Left		8
#define Index_Evade_Right		9
#define Index_Attack_1			10
#define Index_Shoot_1			11
#define Index_Shoot_2			12
#define Index_Shoot_3			13
#define Index_Shock_1			14
#define Index_Shock_2			15
#define Index_Shock_2_Boom		16
#define Index_Shock_2_Miss		17
#define Index_Stealth_Back		18
#define Index_Snealth			19
#define Index_Summon			20
#define Index_Throw_1			21
#define Index_Throw_2			22
#define Index_Throw_3			23
#define Index_Skill_Ultra		24
#define Index_Weak				25
#define Index_Weak_Hit_L		26
#define Index_Weak_Hit_H		27
#define Index_Weak_Start_L		28
#define Index_Weak_Start_H		29
#define Index_Hit_H				30
#define Index_Die				31
