#pragma once
#define Name_Attack_1_Left			L"Attack_1_Left"
#define Name_Attack_1_Right			L"Attack_1_Right"
#define Name_Attack_2				L"Attack_2"
#define Name_Run_Attack_BS			L"Run_Attack_BS"
#define Name_Attack_Run_Loop		L"Attack_Run_Loop"
#define Name_Die					L"Die"
#define Name_Die_Back				L"Die_Back"
#define Name_FastRun_Loop			L"FastRun_Loop"
#define Name_Freefall				L"Freefall"
#define Name_Freefall_Low			L"Freefall_Low"
#define Name_Hit_Back				L"Hit_Back"
#define Name_Hit_H					L"Hit_H"
#define Name_Hit_L_1				L"Hit_L_1"
#define Name_Hit_L_1_Light			L"Hit_L_1_Light"
#define Name_Hit_L_2				L"Hit_L_2"
#define Name_Hit_L_2_Light			L"Hit_L_2_Light"
#define Name_Hit_Shake				L"Hit_Shake"
#define Name_Hit_Throw				L"Hit_Throw"
#define Name_Hit_Throw_Low			L"Hit_Throw_Low"
#define Name_KnockDown				L"KnockDown"
#define Name_Run_AS					L"Run_AS"
#define Name_Run_Attack				L"Run_Attack"
#define Name_Run_Attack_Quick		L"Run_Attack_Quick"
#define Name_StandBy				L"StandBy"
#define Name_StandUp				L"StandUp"
#define Name_Throw_01				L"Throw_01"
#define Name_Throw_02				L"Throw_02"
#define Name_Throw_Blow				L"Throw_Blow"
#define Name_Walk_Backward			L"Walk_Backward"
#define Name_Walk_Forward			L"Walk_Forward"

#define Index_Attack_1_Left			0
#define Index_Attack_1_Right		1
#define Index_Attack_2				2
#define Index_Run_Attack_BS			3
#define Index_Attack_Run_Loop		4
#define Index_Die					5
#define Index_Die_Back				6
#define Index_FastRun_Loop			7
#define Index_Freefall				8
#define Index_Freefall_Low			9
#define Index_Hit_Back				10
#define Index_Hit_H					11
#define Index_Hit_L_1				12
#define Index_Hit_L_1_Light			13
#define Index_Hit_L_2				14
#define Index_Hit_L_2_Light			15
#define Index_Hit_Shake				16
#define Index_Hit_Throw				17
#define Index_Hit_Throw_Low			18
#define Index_KnockDown				19
#define Index_Run_AS				20
#define Index_Run_Attack			21
#define Index_Run_Attack_Quick		22
#define Index_StandBy				23
#define Index_StandUp				24
#define Index_Throw_01				25
#define Index_Throw_02				26
#define Index_Throw_Blow			27
#define Index_Walk_Backward			28
#define Index_Walk_Forward			29
