#pragma once
#define Name_Appear						L"Appear"
#define Name_Attack_1					L"Attack_1"
#define Name_Attack_2					L"Attack_2"
#define Name_Attack_3					L"Attack_3"
#define Name_Attack_3_Branch			L"Attack_3_Branch"
#define Name_Attack_4					L"Attack_4"
#define Name_Attack_4_Branch			L"Attack_4_Branch"
#define Name_Attack_5					L"Attack_5"
#define Name_Attack_QTE					L"Attack_QTE"
#define Name_Die						L"Die"
#define Name_EvadeBackward				L"EvadeBackward"
#define Name_EvadeForward				L"EvadeForward"
#define Name_Failure_01_Idle			L"Failure_01_Idle"
#define Name_Hit_H						L"Hit_H"
#define Name_Hit_L						L"Hit_L"
#define Name_Idle_01					L"Idle_01"
#define Name_Idle_1to2					L"Idle_1to2"
#define Name_Idle_02					L"Idle_02"
#define Name_Idle_2to3					L"Idle_2to3"
#define Name_Idle_03					L"Idle_03"
#define Name_Idle_3to4					L"Idle_3to4"
#define Name_Idle_4to5					L"Idle_4to5"
#define Name_Idle01_AS					L"Idle01_AS"
#define Name_Idle01_BS					L"Idle01_BS"
#define Name_Idle01_Loop				L"Idle01_Loop"
#define Name_Idle02_AS					L"Idle02_AS"
#define Name_Idle02_BS					L"Idle02_BS"
#define Name_Idle02_Loop				L"Idle02_Loop"
#define Name_Idle03_AS					L"Idle03_AS"
#define Name_Idle03_BS					L"Idle03_BS"
#define Name_Idle03_Loop				L"Idle03_Loop"
#define Name_Idle04_AS					L"Idle04_AS"
#define Name_Idle04_BS					L"Idle04_BS"
#define Name_Idle04_Loop				L"Idle04_Loop"
#define Name_Idle05_AS					L"Idle05_AS"
#define Name_Idle05_BS					L"Idle05_BS"
#define Name_Idle05_Loop				L"Idle05_Loop"
#define Name_Jump_00					L"Jump_00"
#define Name_Jump_01					L"Jump_01"
#define Name_Jump_02					L"Jump_02"
#define Name_Run						L"Run"
#define Name_RunBS						L"RunBS"
#define Name_RunStopLeft				L"RunStopLeft"
#define Name_RunStopRight				L"RunStopRight"
#define Name_Skill_10					L"Skill_10"
#define Name_SpecialStun				L"SpecialStun"
#define Name_SpecialStun_BS				L"SpecialStun_BS"
#define Name_StandBy					L"StandBy"
#define Name_Stun						L"Stun"
#define Name_SwitchIn					L"SwitchIn"
#define Name_SwitchOut					L"SwitchOut"
#define Name_UI_StandBy_No_Weapon_0		L"UI_StandBy_No_Weapon_0"
#define Name_UI_StandBy_No_Weapon_1		L"UI_StandBy_No_Weapon_1"
#define Name_Victory_01					L"Victory_01"
#define Name_Victory_Idle				L"Victory_Idle"

#define Index_Appear					0
#define Index_Attack_1					1
#define Index_Attack_2					2
#define Index_Attack_3					3
#define Index_Attack_3_Branch			4
#define Index_Attack_4					5
#define Index_Attack_4_Branch			6
#define Index_Attack_5					7
#define Index_Attack_QTE				8
#define Index_Die						9
#define Index_EvadeBackward				10
#define Index_EvadeForward				11
#define Index_Failure_01_Idle			12
#define Index_Hit_H						13
#define Index_Hit_L						14
#define Index_Idle_01					15
#define Index_Idle_1to2					16
#define Index_Idle_02					17
#define Index_Idle_2to3					18
#define Index_Idle_03					19
#define Index_Idle_3to4					20
#define Index_Idle_4to5					21
#define Index_Idle01_AS					22
#define Index_Idle01_BS					23
#define Index_Idle01_Loop				24
#define Index_Idle02_AS					25
#define Index_Idle02_BS					26
#define Index_Idle02_Loop				27
#define Index_Idle03_AS					28
#define Index_Idle03_BS					29
#define Index_Idle03_Loop				30
#define Index_Idle04_AS					31
#define Index_Idle04_BS					32
#define Index_Idle04_Loop				33
#define Index_Idle05_AS					34
#define Index_Idle05_BS					35
#define Index_Idle05_Loop				36
#define Index_Jump_00					37
#define Index_Jump_01					38
#define Index_Jump_02					39
#define Index_Run						40
#define Index_RunBS						41
#define Index_RunStopLeft				42
#define Index_RunStopRight				43
#define Index_Skill_10					44
#define Index_SpecialStun				45
#define Index_SpecialStun_BS			46
#define Index_StandBy					47
#define Index_Stun						48
#define Index_SwitchIn					49
#define Index_SwitchOut					50
#define Index_UI_StandBy_No_Weapon_0	51
#define Index_UI_StandBy_No_Weapon_1	52
#define Index_Victory_01				53
#define Index_Victory_Idle				54


#define Sound_Attack_1_Effect		L"K_Attack_0.wav"
#define Sound_Attack_2_Effect		L"K_Attack_1.wav"
#define Sound_Attack_3_Effect		L"K_Attack_2.wav"
#define Sound_Attack_4_Effect		L"K_Attack_3.wav"
#define Sound_Attack_5_Effect		L"K_Attack_4.wav"
#define Sound_Attack_Voice_0		L"K_Attack_Voice_0.wav"	
#define Sound_Attack_Voice_1		L"K_Attack_Voice_1.wav"	
#define Sound_Attack_Voice_2		L"K_Attack_Voice_2.wav"	
#define Sound_Attack_Voice_3		L"K_Attack_Voice_3.wav"
#define Sound_Attack_Voice_4		L"K_Attack_Voice_4.wav"
#define Sound_Attack_Voice_5		L"K_Attack_Voice_5.wav"
#define Sound_Attack_Voice_6		L"K_Attack_Voice_6.wav"	
#define Sound_Branch_0 				L"K_Charge_0.wav"
#define Sound_Branch_1				L"K_Charge_1.wav"
#define Sound_Branch_Voice_0		L"K_Charge_Voice_0.wav"
#define Sound_Branch_Voice_1		L"K_Charge_Voice_1.wav"
#define Sound_Dead					L"K_DEAD.wav"
#define Sound_Evade_0				L"K_Evade_0.wav"
#define Sound_Evade_1				L"K_Evade_1.wav"
#define Sound_HIT_0					L"K_HIT_0.wav"
#define Sound_HIT_1					L"K_HIT_1.wav"
#define Sound_HIT_2					L"K_HIT_2.wav"
#define Sound_HIT_3					L"K_HIT_3.wav"
#define Sound_RUN_0					L"K_Run_0.wav"
#define Sound_RUN_1					L"K_Run_1.wav"
#define Sound_RUN_2					L"K_Run_2.wav"
#define Sound_RUN_3					L"K_Run_3.wav"
#define Sound_RUN_4					L"K_Run_4.wav"
#define Sound_Ult_Att_0				L"K_Ult_Att_0.wav"
#define Sound_Ult_Att_1				L"K_Ult_Att_1.wav"
#define Sound_Ult_Att_2				L"K_Ult_Att_2.wav"
#define Sound_Ult_Att_3				L"K_Ult_Att_3.wav"
#define Sound_Ult_Start				L"K_Ult_Start.wav"
#define Sound_Ult_Start_Voice		L"K_Ult_Start_Voice.wav"
