#pragma once
#define Name_Appear								L"appear"
#define Name_attack_01_standby					L"attack_01_standby"
#define Name_attack_01_combat					L"attack_01_combat"
#define Name_attack_charge_01_as				L"attack_charge_01_as"
#define Name_attack_02							L"attack_02"
#define Name_attack_charge_02_as				L"attack_charge_02_as"
#define Name_attack_charge_02_bs				L"attack_charge_02_bs"
#define Name_attack_charge_02_loop				L"attack_charge_02_loop"
#define Name_attack02_02_as						L"attack02_02_as"
#define Name_attack02_02_bs						L"attack02_02_bs"
#define Name_attack02_02_loop					L"attack02_02_loop"
#define Name_attack_charge_02_loop_unit			L"attack_charge_02_loop_unit"
#define Name_branch								L"branch"
#define Name_charge_01							L"charge_01"
#define Name_charge_01_c3ult					L"charge_01_c3ult"
#define Name_charge_01_quick					L"charge_01_quick"
#define Name_combat								L"combat"
#define Name_combattostandby					L"combattostandby"
#define Name_Die								L"die"
#define Name_EvadeBackward						L"evadebackward"
#define Name_EvadeForward						L"evadeforward"
#define Name_failure_01							L"failure_01"
#define Name_failure_loop						L"failure_loop"
#define Name_hit_die_fly						L"hit_die_fly"
#define Name_hit_h								L"hit_h"
#define Name_hit_l								L"hit_l"
#define Name_qte								L"qte"
#define Name_Run								L"run"
#define Name_RunBS								L"runbs"
#define Name_RunStopLeft						L"runstopleft"
#define Name_RunStopRight						L"runstopright"
#define Name_skill_01							L"skill_01"
#define Name_skill_ultra_01						L"skill_ultra_01"
#define Name_streaming_attack_01				L"streaming_attack_01"
#define Name_streaming_attack_bs				L"streaming_attack_bs"
#define Name_streaming_attack_loop				L"streaming_attack_loop"
#define Name_streaming_branch					L"streaming_branch"
#define Name_stun								L"stun"
#define Name_stun_a								L"stun_a"
#define Name_switchin							L"switchin"
#define Name_switchrole							L"switchrole"
#define Name_ui_standby							L"ui_standby"
#define Name_ui_standby_back					L"ui_standby_back"
#define Name_ul_turnaround						L"ul_turnaround"
#define Name_ultra								L"ultra"
#define Name_ultra_c3_sakurafall				L"ultra_c3_sakurafall"
#define Name_weapon_castdown					L"weapon_castdown"
#define Name_weapon_circlecut					L"weapon_circlecut"
#define Name_weapon_groundfield					L"weapon_groundfield"
#define Name_weapon_quantumdash					L"weapon_quantumdash"
#define Name_weapon_spacetear					L"weapon_spacetear"
#define Name_weapon_sprintcut					L"weapon_sprintcut"
#define Name_weapon_whirl						L"weapon_whirl"
#define Name_win								L"win"
#define Name_win_idle							L"win_idle"
#define Name_attack_03							L"attack_03"
#define Name_attack_04							L"attack_04"
#define Name_attack_05							L"attack_05"
#define Name_StandBy							L"idle"

#define Index_Appear							0	
#define Index_attack_01_standby					1	
#define Index_attack_01_combat					2	
#define Index_attack_charge_01_as				3	
#define Index_attack_02							4	
#define Index_attack_charge_02_as				5	
#define Index_attack_charge_02_bs				6	
#define Index_attack_charge_02_loop				7	
#define Index_attack02_02_as					8	
#define Index_attack02_02_bs					9	
#define Index_attack02_02_loop					10	
#define Index_attack_charge_02_loop_unit		11	
#define Index_branch							12	
#define Index_charge_01							13	
#define Index_charge_01_c3ult					14	
#define Index_charge_01_quick					15	
#define Index_combat							16	
#define Index_combattostandby					17	
#define Index_Die								18	
#define Index_EvadeBackward						19	
#define Index_EvadeForward						20	
#define Index_failure_01						21	
#define Index_failure_loop						22	
#define Index_hit_die_fly						23	
#define Index_hit_h								24	
#define Index_hit_l								25	
#define Index_qte								26	
#define Index_Run								27	
#define Index_RunBS								28	
#define Index_RunStopLeft						29	
#define Index_RunStopRight						30	
#define Index_skill_01							31	
#define Index_skill_ultra_01					32	
#define Index_streaming_attack_01				33	
#define Index_streaming_attack_bs				34	
#define Index_streaming_attack_loop				35	
#define Index_streaming_branch					36	
#define Index_stun								37	
#define Index_stun_a							38	
#define Index_switchin							39	
#define Index_switchrole						40	
#define Index_ui_standby						41	
#define Index_ui_standby_back					42	
#define Index_ul_turnaround						43	
#define Index_ultra								44	
#define Index_ultra_c3_sakurafall				45	
#define Index_weapon_castdown					46	
#define Index_weapon_circlecut					47	
#define Index_weapon_groundfield				48	
#define Index_weapon_quantumdash				49	
#define Index_weapon_spacetear					50	
#define Index_weapon_sprintcut					51	
#define Index_weapon_whirl						52	
#define Index_win								53	
#define Index_win_idle							54	
#define Index_attack_03							55	
#define Index_attack_04							56	
#define Index_attack_05							57	
#define Index_StandBy							58	