#pragma once
#define Name_Attack_1					L"Attack_1"
#define Name_Attack_2					L"Attack_2"
#define Name_Attack_2_BS				L"Attack_2_BS"
#define Name_Attack_2_Run				L"Attack_2_Run"
#define Name_Attack_3					L"Attack_3"
#define Name_Attack_3_AS				L"Attack_3_AS"
#define Name_Attack_3_BS				L"Attack_3_BS"
#define Name_Attack_Die					L"Attack_Die"
#define Name_Born						L"Born"
#define Name_Bury_AS					L"Bury_AS"
#define Name_Bury_BS					L"Bury_BS"
#define Name_Bury_Loop					L"Bury_Loop"
#define Name_Hit_H						L"Hit_H"
#define Name_Hit_H_Early				L"Hit_H_Early"
#define Name_Hit_L						L"Hit_L"
#define Name_Hit_L_Early				L"Hit_L_Early"
#define Name_Hit_Throw					L"Hit_Throw"
#define Name_Hit_Throw_Low				L"Hit_Throw_Low"
#define Name_KnockDown					L"KnockDown"
#define Name_StandBy					L"StandBy"
#define Name_Throw_01					L"Throw_01"
#define Name_Throw_02					L"Throw_02"
#define Name_Throw_Blow					L"Throw_Blow"
#define Name_Walk_Forward				L"Walk_Forward"
#define Name_Walk_Left					L"Walk_Left"
#define Name_Walk_Right					L"Walk_Right"


#define Index_Attack_1					0
#define Index_Attack_2					1
#define Index_Attack_2_BS				2
#define Index_Attack_2_Run				3
#define Index_Attack_3					4
#define Index_Attack_3_AS				5
#define Index_Attack_3_BS				6
#define Index_Attack_Die				7
#define Index_Born						8
#define Index_Bury_AS					9
#define Index_Bury_BS					10
#define Index_Bury_Loop					11
#define Index_Hit_H						12
#define Index_Hit_H_Early				13
#define Index_Hit_L						14
#define Index_Hit_L_Early				15
#define Index_Hit_Throw					16
#define Index_Hit_Throw_Low				17
#define Index_KnockDown					18
#define Index_StandBy					19
#define Index_Throw_01					20
#define Index_Throw_02					21
#define Index_Throw_Blow				22
#define Index_Walk_Forward				23
#define Index_Walk_Left					24
#define Index_Walk_Right				25
