#pragma once

#define Index_Appear					0	
#define Index_Attack1_StandBy			1	
#define Index_Attack1_Combat			2	
#define Index_Attack2					3	
#define Index_Attack3					4	
#define Index_Attack4					5	
#define Index_Attack5					6	
#define Index_Attack_QTE				7	
#define Index_Charge1					8	
#define Index_Charge1_AS				9	
#define Index_Charge1_Quick				10	
#define Index_Combat					11	
#define Index_Combat_AutoStandBy		12	
#define Index_Die						13	
#define Index_EvadeBackward				14	
#define Index_EvadeForward				15	
#define Index_Failure					16	
#define Index_Failure_Loop				17	
#define Index_Hit_H						18	
#define Index_Hit_L						19	
#define Index_Idle1						20	
#define Index_Run						21	
#define Index_RunBS						22	
#define Index_RunStopLeft				23	
#define Index_RunStopRight				24	
#define Index_StandBy					25	
#define Index_StandBy_Back				26	
#define Index_Stun						27	
#define Index_SwitchIn					28	
#define Index_SwitchOut					29	
#define Index_TurnAround				30	
#define Index_Ultra						31	
#define Index_Victory					32	
#define Index_Victory_Idle				33	


#define Name_Appear					L"Appear"
#define Name_Attack1_StandBy		L"Attack1_StandBy"
#define Name_Attack1_Combat			L"Attack1_Combat"
#define Name_Attack2				L"Attack2"
#define Name_Attack3				L"Attack3"
#define Name_Attack4				L"Attack4"
#define Name_Attack5				L"Attack5"
#define Name_Attack_QTE				L"Attack_QTE"
#define Name_Charge1				L"Charge1"
#define Name_Charge1_AS				L"Charge1_AS"
#define Name_Charge1_Quick			L"Charge1_Quick"
#define Name_Combat					L"Combat"
#define Name_Combat_AutoStandBy		L"Combat_AutoStandBy"
#define Name_Die					L"Die"
#define Name_EvadeBackward			L"EvadeBackward"
#define Name_EvadeForward			L"EvadeForward"
#define Name_Failure				L"Failure"
#define Name_Failure_Loop			L"Failure_Loop"
#define Name_Hit_H					L"Hit_H"
#define Name_Hit_L					L"Hit_L"
#define Name_Idle1					L"Idle1"
#define Name_Run					L"Run"
#define Name_RunBS					L"RunBS"
#define Name_RunStopLeft			L"RunStopLeft"
#define Name_RunStopRight			L"RunStopRight"
#define Name_StandBy				L"StandBy"
#define Name_StandBy_Back			L"StandBy_Back"
#define Name_Stun					L"Stun"
#define Name_SwitchIn				L"SwitchIn"
#define Name_SwitchOut				L"SwitchOut"
#define Name_TurnAround				L"TurnAround"
#define Name_Ultra					L"Ultra"
#define Name_Victory				L"Victory"
#define Name_Victory_Idle			L"Victory_Idle"