#pragma once
#define Name_APPEAR				L"APPEAR"
#define Name_IDLE				L"IDLE"
#define Name_RUN_L				L"RUN_L"
#define Name_RUN_R				L"RUN_R"
#define Name_RUN_F				L"RUN_F"
#define Name_RUN_B				L"RUN_B"
#define Name_SHOOT_1			L"SHOOT_1"
#define Name_SHOOT_2			L"SHOOT_2"
#define Name_SHOOT_3			L"SHOOT_3"
#define Name_SHOOT_FIREFALL		L"SHOOT_FIREFALL"
#define Name_LASER_BS			L"LASER_BS"
#define Name_LASER_LOOP			L"LASER_LOOP"
#define Name_Laser_AS			L"Laser_AS"
#define Name_HIT_L				L"HIT_L"
#define Name_HIT_H				L"HIT_H"
#define Name_HIT_FRONT			L"HIT_FRONT"
#define Name_HIT_BACK			L"HIT_BACK"
#define Name_Throw_0			L"Throw_0"
#define Name_Throw_1			L"Throw_1"
#define Name_Throw_2			L"Throw_2"
#define Name_Throw_Blow			L"Throw_Blow"
#define Name_Throw_Low			L"Throw_Low"
#define Name_KnockDown			L"KnockDown"
#define Name_StandUp			L"StandUp"
#define Name_Stun				L"Stun"
#define Name_DIE				L"DIE"
#define Name_DIE_FLY			L"DIE_FLY"

#define Index_APPEAR			0
#define Index_IDLE				1
#define Index_RUN_L				2
#define Index_RUN_R				3
#define Index_RUN_F				4
#define Index_RUN_B				5
#define Index_SHOOT_1			6
#define Index_SHOOT_2			7
#define Index_SHOOT_3			8
#define Index_SHOOT_FIREFALL	9
#define Index_LASER_BS			10
#define Index_LASER_LOOP		11
#define Index_Laser_AS			12
#define Index_HIT_L				13
#define Index_HIT_H				14
#define Index_HIT_FRONT			15
#define Index_HIT_BACK			16
#define Index_Throw_0			17
#define Index_Throw_1			18
#define Index_Throw_2			19
#define Index_Throw_Blow		20
#define Index_Throw_Low			21
#define Index_KnockDown			22
#define Index_StandUp			23
#define Index_Stun				24
#define Index_DIE				25
#define Index_DIE_FLY			26
