#pragma once
#define Name_StandBy					L"StandBy"
#define Name_Walk_Forward				L"Walk_Forward"
#define Name_Walk_Back					L"Walk_Back"
#define Name_Walk_Left					L"Walk_Left"
#define Name_Walk_Right					L"Walk_Right"
#define Name_Attack_1					L"Attack_1"
#define Name_Attack_2					L"Attack_2"
#define Name_Attack_2_1					L"Attack_2_1"
#define Name_Attack_2_Loop				L"Attack_2_Loop"
#define Name_Attack_3					L"Attack_3"
#define Name_Attack_4_Start				L"Attack_4_Start"
#define Name_Attack_4_Loop				L"Attack_4_Loop"
#define Name_Attack_4_End				L"Attack_4_End"
#define Name_Attack_Unique01			L"Attack_Unique01"
#define Name_Born						L"Born"
#define Name_Die						L"Die"
#define Name_Die_Back					L"Die_Back"
#define Name_Die_Fly					L"Die_Fly"
#define Name_KnockDown					L"KnockDown"
#define Name_Stun						L"Stun"
#define Name_StandUp					L"StandUp"
#define Name_Throw_01					L"Throw_01"
#define Name_Throw_02					L"Throw_02"
#define Name_Hit_Throw					L"Hit_Throw"
#define Name_Hit_Throw_Low				L"Hit_Throw_Low"
#define Name_Throw_Blow					L"Throw_Blow"
#define Name_Hit_Front					L"Hit_Front"
#define Name_Hit_Front_L				L"Hit_Front_L"
#define Name_Hit_Back					L"Hit_Back"
#define Name_Hit_H						L"Hit_H"
#define Name_Hit_L						L"Hit_L"
#define Name_Hit_Shake					L"Hit_Shake"
#define Name_Hit_Shake_1				L"Hit_Shake_1"
#define Name_Defend						L"Defend"

#define Index_StandBy					0
#define Index_Walk_Forward				1
#define Index_Walk_Back					2
#define Index_Walk_Left					3
#define Index_Walk_Right				4
#define Index_Attack_1					5
#define Index_Attack_2					6
#define Index_Attack_2_1				7
#define Index_Attack_2_Loop				8
#define Index_Attack_3					9
#define Index_Attack_4_Start			10
#define Index_Attack_4_Loop				11
#define Index_Attack_4_End				12
#define Index_Attack_Unique01			13
#define Index_Born						14
#define Index_Die						15
#define Index_Die_Back					16
#define Index_Die_Fly					17
#define Index_KnockDown					18
#define Index_Stun						19
#define Index_StandUp					20
#define Index_Throw_01					21
#define Index_Throw_02					22
#define Index_Hit_Throw					23
#define Index_Hit_Throw_Low				24
#define Index_Throw_Blow				25
#define Index_Hit_Front					26
#define Index_Hit_Front_L				27
#define Index_Hit_Back					28
#define Index_Hit_H						29
#define Index_Hit_L						30
#define Index_Hit_Shake					31
#define Index_Hit_Shake_1				32
#define Index_Defend					33