#pragma once
#define Name_standby					L"standby"
#define Name_attack_1_as				L"attack_1_as"
#define Name_attack_1_atk				L"attack_1_atk"
#define Name_attack_1_bs				L"attack_1_bs"
#define Name_attack_2_atk_1				L"attack_2_atk_1"
#define Name_attack_2_atk_2				L"attack_2_atk_2"
#define Name_attack_2_atk_3				L"attack_2_atk_3"
#define Name_attack_2_atk_as_long		L"attack_2_atk_as_long"
#define Name_attack_2_bs				L"attack_2_bs"
#define Name_born						L"born"
#define Name_defend						L"defend"
#define Name_defendattack				L"defendattack"
#define Name_die						L"die"
#define Name_die_back					L"die_back"
#define Name_die_fly					L"die_fly"
#define Name_hit_back					L"hit_back"
#define Name_hit_front					L"hit_front"
#define Name_hit_front_l				L"hit_front_l"
#define Name_hit_h						L"hit_h"
#define Name_hit_left					L"hit_left"
#define Name_hit_right					L"hit_right"
#define Name_hit_shake					L"hit_shake"
#define Name_hit_throw					L"hit_throw"
#define Name_hit_throw_low				L"hit_throw_low"
#define Name_knockdown					L"knockdown"
#define Name_run						L"run"
#define Name_standup					L"standup"
#define Name_stay						L"stay"
#define Name_stun						L"stun"
#define Name_teleport					L"teleport"
#define Name_throw_01					L"throw_01"
#define Name_throw_02					L"throw_02"
#define Name_throw_blow					L"throw_blow"
#define Name_walk_b						L"walk_b"
#define Name_walk_f						L"walk_f"
#define Name_walk_l						L"walk_l"
#define Name_walk_r						L"walk_r"

#define Index_standby					0
#define Index_attack_1_as				1
#define Index_attack_1_atk				2
#define Index_attack_1_bs				3
#define Index_attack_2_atk_1			4
#define Index_attack_2_atk_2			5
#define Index_attack_2_atk_3			6
#define Index_attack_2_atk_as_long		7
#define Index_attack_2_bs				8
#define Index_born						9
#define Index_defend					10
#define Index_defendattack				11
#define Index_die						12
#define Index_die_back					13
#define Index_die_fly					14
#define Index_hit_back					15
#define Index_hit_front					16
#define Index_hit_front_l				17
#define Index_hit_h						18
#define Index_hit_left					19
#define Index_hit_right					20
#define Index_hit_shake					21
#define Index_hit_throw					22
#define Index_hit_throw_low				23
#define Index_knockdown					24
#define Index_run						25
#define Index_standup					26
#define Index_stay						27
#define Index_stun						28
#define Index_teleport					29
#define Index_throw_01					30
#define Index_throw_02					31
#define Index_throw_blow				32
#define Index_walk_b					33
#define Index_walk_f					34
#define Index_walk_l					35
#define Index_walk_r					36
