#pragma once
#define Name_APPEAR				L"APPEAR"
#define Name_ATTACK_1			L"ATTACK_1"
#define Name_ATTACK_2			L"ATTACK_2"
#define Name_ATTACK3			L"ATTACK3"
#define Name_BOM_READY			L"BOM_READY"
#define Name_DIE				L"DIE"
#define Name_DIE_BACK			L"DIE_BACK"
#define Name_DIE_FLY			L"DIE_FLY"
#define Name_FREE_FALL			L"FREE_FALL"
#define Name_FREE_FALL_LOW		L"FREE_FALL_LOW"
#define Name_HIDE				L"HIDE"
#define Name_HIT_BACK			L"HIT_BACK"
#define Name_HIT_H				L"HIT_H"
#define Name_HIT_EARLY			L"HIT_EARLY"
#define Name_HIT_L				L"HIT_L"
#define Name_HIT_L_EARLY		L"HIT_L_EARLY"
#define Name_HIT_LEFT			L"HIT_LEFT"
#define Name_HIT_RIGHT			L"HIT_RIGHT"
#define Name_HIT_SHAKE			L"HIT_SHAKE"
#define Name_JUMP_BACK			L"JUMP_BACK"
#define Name_KNOCK_DOWN			L"KNOCK_DOWN"
#define Name_RUN				L"RUN"
#define Name_STAND				L"STAND"
#define Name_STAND_UP			L"STAND_UP"
#define Name_STUN				L"STUN"
#define Name_THROW_0			L"THROW_0"
#define Name_THROW_1			L"THROW_1"
#define Name_THROW_2			L"THROW_2"
#define Name_THROW_BLOW			L"THROW_BLOW"
#define Name_THROW_LOW			L"THROW_LOW"
#define Name_WALK_BACKWARD		L"WALK_BACKWARD"
#define Name_WALK_FORWARD		L"WALK_FORWARD"
#define Name_WALK_LEFT			L"WALK_LEFT"
#define Name_WALK_RIGHT			L"WALK_RIGHT"

#define Index_APPEAR			0
#define Index_ATTACK1			1
#define Index_ATTACK_2			2
#define Index_ATTACK3			3
#define Index_BOM_READY			4
#define Index_DIE				5
#define Index_DIE_BACK			6
#define Index_DIE_FLY			7
#define Index_FREE_FALL			8
#define Index_FREE_FALL_LOW		9
#define Index_HIDE				10
#define Index_HIT_BACK			11
#define Index_HIT_H				12
#define Index_HIT_EARLY			13
#define Index_HIT_L				14
#define Index_HIT_L_EARLY		15
#define Index_HIT_LEFT			16
#define Index_HIT_RIGHT			17
#define Index_HIT_SHAKE			18
#define Index_JUMP_BACK			19
#define Index_KNOCK_DOWN		20
#define Index_RUN				21
#define Index_STAND				22
#define Index_STAND_UP			23
#define Index_STUN				24
#define Index_THROW_0			25
#define Index_THROW_1			26
#define Index_THROW_2			27
#define Index_THROW_BLOW		28
#define Index_THROW_LOW			29
#define Index_WALK_BACKWARD		30
#define Index_WALK_FORWARD		31
#define Index_WALK_LEFT			32
#define Index_WALK_RIGHT		33
