#pragma once
#define Name_Ganesha_ActivateRampage		L"ActivateRampage"
#define Name_Ganesha_Attack01				L"Attack01"
#define Name_Ganesha_Born					L"Born"
#define Name_Ganesha_Burst01				L"Burst01"
#define Name_Ganesha_Burst02				L"Burst02"
#define Name_Ganesha_Die					L"Die"
#define Name_Ganesha_Jump_Back				L"Jump_Back"
#define Name_Ganesha_Jump_Turn				L"Jump_Turn"
#define Name_Ganesha_Roll01					L"Roll01"
#define Name_Ganesha_Roll02					L"Roll02"
#define Name_Ganesha_Run					L"Run"
#define Name_Ganesha_Stamp					L"Stamp"
#define Name_Ganesha_StandBy				L"StandBy"
#define Name_Ganesha_Weak					L"Weak"
#define Name_Ganesha_Weak_End				L"Weak_End"
#define Name_Ganesha_Weak_Hit				L"Weak_Hit"
#define Name_Ganesha_Weak_Loop				L"Weak_Loop"
#define Name_Ganesha_Weak_Start				L"Weak_Start"

#define Index_Ganesha_ActivateRampage		0
#define Index_Ganesha_Attack01				1
#define Index_Ganesha_Born					2
#define Index_Ganesha_Burst01				3
#define Index_Ganesha_Burst02				4
#define Index_Ganesha_Die					5
#define Index_Ganesha_Jump_Back				6
#define Index_Ganesha_Jump_Turn				7
#define Index_Ganesha_Roll01				8
#define Index_Ganesha_Roll02				9
#define Index_Ganesha_Run					10
#define Index_Ganesha_Stamp					11
#define Index_Ganesha_StandBy				12
#define Index_Ganesha_Weak					13
#define Index_Ganesha_Weak_End				14
#define Index_Ganesha_Weak_Hit				15
#define Index_Ganesha_Weak_Loop				16
#define Index_Ganesha_Weak_Start			17
