#pragma once
#define Name_Appear						L"Appear"
#define Name_Attack_1					L"Attack_1"
#define Name_Attack_2					L"Attack_2"
#define Name_Attack_3					L"Attack_3"
#define Name_Attack_3_Branch			L"Attack_3_Branch"
#define Name_Attack_4					L"Attack_4"
#define Name_Attack_4_Branch			L"Attack_4_Branch"
#define Name_Attack_5					L"Attack_5"
#define Name_Attack_QTE					L"Attack_QTE"
#define Name_Die						L"Die"
#define Name_EvadeBackward				L"EvadeBackward"
#define Name_EvadeForward				L"EvadeForward"
#define Name_Failure					L"Failure"
#define Name_Failure_Idle				L"Failure_Idle"
#define Name_Hit_H						L"Hit_H"
#define Name_Hit_L						L"Hit_L"
#define Name_Idle_01					L"Idle_01"
#define Name_Idle_02					L"Idle_02"
#define Name_Idle_03					L"Idle_03"
#define Name_Run						L"Run"
#define Name_RunBS						L"RunBS"
#define Name_RunStopLeft				L"RunStopLeft"
#define Name_RunStopRight				L"RunStopRight"
#define Name_StandBy					L"StandBy"
#define Name_Stun						L"Stun"
#define Name_SwitchIn					L"SwitchIn"
#define Name_SwitchOut					L"SwitchOut"
#define Name_Ultra						L"Ultra"
#define Name_Victory					L"Victory_01"
#define Name_Victory_Idle				L"Victory_Idle"

#define Index_Appear					0
#define Index_Attack_1					1
#define Index_Attack_2					2
#define Index_Attack_3					3
#define Index_Attack_3_Branch			4
#define Index_Attack_4					5
#define Index_Attack_4_Branch			6
#define Index_Attack_5					7
#define Index_Attack_QTE				8
#define Index_Die						9
#define Index_EvadeBackward				10
#define Index_EvadeForward				11
#define Index_Failure					12
#define Index_Failure_Idle				13
#define Index_Hit_H						14
#define Index_Hit_L						15
#define Index_Idle_01					16
#define Index_Idle_02					17
#define Index_Idle_03					18
#define Index_Run						19
#define Index_RunBS						20
#define Index_RunStopLeft				21
#define Index_RunStopRight				22
#define Index_WeaponSkill				23
#define Index_StandBy					24
#define Index_Stun						25
#define Index_SwitchIn					26
#define Index_SwitchOut					27
#define Index_Ultra						28
#define Index_Victory					29
#define Index_Victory_Idle				30


#define Sound_Attack_1_Effect		L"K_Attack_0.wav"
#define Sound_Attack_2_Effect		L"K_Attack_1.wav"
#define Sound_Attack_3_Effect		L"K_Attack_2.wav"
#define Sound_Attack_4_Effect		L"K_Attack_3.wav"
#define Sound_Attack_5_Effect		L"K_Attack_4.wav"
#define Sound_Attack_Voice_0		L"K_Attack_Voice_0.wav"	
#define Sound_Attack_Voice_1		L"K_Attack_Voice_1.wav"	
#define Sound_Attack_Voice_2		L"K_Attack_Voice_2.wav"	
#define Sound_Attack_Voice_3		L"K_Attack_Voice_3.wav"
#define Sound_Attack_Voice_4		L"K_Attack_Voice_4.wav"
#define Sound_Attack_Voice_5		L"K_Attack_Voice_5.wav"
#define Sound_Attack_Voice_6		L"K_Attack_Voice_6.wav"	
#define Sound_Branch_0 				L"K_Charge_0.wav"
#define Sound_Branch_1				L"K_Charge_1.wav"
#define Sound_Branch_Voice_0		L"K_Charge_Voice_0.wav"
#define Sound_Branch_Voice_1		L"K_Charge_Voice_1.wav"
#define Sound_Dead					L"K_DEAD.wav"
#define Sound_Evade_0				L"K_Evade_0.wav"
#define Sound_Evade_1				L"K_Evade_1.wav"
#define Sound_HIT_0					L"K_HIT_0.wav"
#define Sound_HIT_1					L"K_HIT_1.wav"
#define Sound_HIT_2					L"K_HIT_2.wav"
#define Sound_HIT_3					L"K_HIT_3.wav"
#define Sound_HIT_3					L"K_HIT_3.wav"
#define Sound_HIT					L"PlayerHit.wav"
#define Sound_RUN_0					L"K_Run_0.wav"
#define Sound_RUN_1					L"K_Run_1.wav"
#define Sound_RUN_2					L"K_Run_2.wav"
#define Sound_RUN_3					L"K_Run_3.wav"
#define Sound_RUN_4					L"K_Run_4.wav"
#define Sound_Ult_Att_0				L"K_Ult_Att_0.wav"
#define Sound_Ult_Att_1				L"K_Ult_Att_1.wav"
#define Sound_Ult_Att_2				L"K_Ult_Att_2.wav"
#define Sound_Ult_Att_3				L"K_Ult_Att_3.wav"
#define Sound_Ult_Start				L"K_Ult_Start.wav"
#define Sound_Ult_Start_Voice		L"K_Ult_Start_Voice.wav"
