#pragma once
#define Name_IDLE						L"IDLE"
#define Name_Walk_Right					L"WALK_RIGHT"
#define Name_Walk_Left					L"WALK_LEFT"
#define Name_Walk_Back					L"WALK_BACK"
#define Name_Run						L"RUN"
#define Name_Attack_1					L"ATTACK_1"
#define Name_Attack_2					L"ATTACK_2"
#define Name_Attack_2_1					L"ATTACK_2_1"
#define Name_Attack_3					L"ATTACK_3"
#define Name_Attack_3_1					L"ATTACK_3_1"
#define Name_Throw_1					L"THROW_1"
#define Name_Throw_2					L"THROW_2"
#define Name_Throw_Blow					L"THROW_BLOW"
#define Name_Knock_Down					L"KNOCK_DOWN"
#define Name_Stand_Up					L"STAND_UP"
#define Name_Stun						L"STUN"
#define Name_Hit_Back					L"HIT_BACK"
#define Name_Hit_Throw					L"HIT_THROW"
#define Name_Hit_Throw_Low				L"HIT_THROW_LOW"
#define Name_Die						L"DIE"
#define Name_Die_Back					L"DIE_BACK"
#define Name_Die_Fly					L"DIE_FLY"

#define Index_IDLE						0
#define Index_Walk_Right				1
#define Index_Walk_Left					2
#define Index_Walk_Back					3
#define Index_Run						4
#define Index_Attack_1					5
#define Index_Attack_2					6
#define Index_Attack_2_1				7
#define Index_Attack_3					8
#define Index_Attack_3_1				9
#define Index_Throw_1					10
#define Index_Throw_2					11
#define Index_Throw_Blow				12
#define Index_Knock_Down				13
#define Index_Stand_Up					14
#define Index_Stun						15
#define Index_Hit_Back					16
#define Index_Hit_Throw					17
#define Index_Hit_Throw_Low				18
#define Index_Die						19
#define Index_Die_Back					20
#define Index_Die_Fly					21
