#pragma once
#define  Anim_Kiana Kiana
#define  Anim_Pistol_USP45 Pistol_USP45
#define  Anim_Pistol_2ndrelic Pistol_2ndrelic
#define  Anim_kiana_catpaw_01_static kiana_catpaw_01_static
#define  Anim_kiana_catpaw_02_dynamic kiana_catpaw_02_dynamic
#define  Anim_Theresa Theresa
#define  Anim_Theresa_Axe Theresa_Axe
#define  Anim_Theresa_Cross Theresa_Cross
#define  Anim_Theresa_Cross_Start Theresa_Cross_Start
#define  Anim_Theresa_Cross_End Theresa_Cross_End
#define  Anim_Theresa_SkillSword Theresa_SkillSword
#define  Anim_Theresa_Sword Theresa_Sword
#define  Anim_Sakura Sakura
#define  Anim_Katana_M26 Katana_M26
#define  Anim_ 
#define  Anim_MB_Bronya MB_Bronya
#define  Anim_MB_Ganesha MB_Ganesha
#define  Anim_MO_Axe MO_Axe
#define  Anim_MO_Lancer MO_Lancer
#define  Anim_MO_Ninza MO_Ninza
#define  Anim_MO_Robot MO_Robot
#define  Anim_MO_Scout MO_Scout
#define  Anim_MO_Spider MO_Spider
#define  Anim_ 
#define  Anim_S01_14 S01_14
#define  Anim_S01_14_nocap S01_14_nocap
#define  Anim_S01_15 S01_15
#define  Anim_S01_15_nocap S01_15_nocap
#define  Anim_S02 S02
#define  Anim_S02_del S02_del
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""
#define Anim1 L""